
#ifndef _QIUNIU_UAPI_CORECTL_H
#define _QIUNIU_UAPI_CORECTL_H

#define _CC_QIUNIU_GET_VERSION		0
#define _CC_QIUNIU_GET_NR_PIPES		1
#define _CC_QIUNIU_GET_NR_TIMERS	2

#define _CC_QIUNIU_GET_DEBUG			3
#   define _CC_QIUNIU_DEBUG_ASSERT		1
#   define _CC_QIUNIU_DEBUG_CONTEXT		2
#   define _CC_QIUNIU_DEBUG_LOCKING		4
#   define _CC_QIUNIU_DEBUG_USER		8
#   define _CC_QIUNIU_DEBUG_MUTEX_RELAXED	16
#   define _CC_QIUNIU_DEBUG_MUTEX_SLEEP		32

#   define _CC_QIUNIU_DEBUG_LEGACY		128
#   define _CC_QIUNIU_DEBUG_TRACE_RELAX		256
#   define _CC_QIUNIU_DEBUG_NET			512

#define _CC_QIUNIU_GET_POLICIES		4
#   define _CC_QIUNIU_SCHED_FIFO	1
#   define _CC_QIUNIU_SCHED_RR		2
#   define _CC_QIUNIU_SCHED_WEAK	4
#   define _CC_QIUNIU_SCHED_SPORADIC	8
#   define _CC_QIUNIU_SCHED_QUOTA	16
#   define _CC_QIUNIU_SCHED_TP		32

#define _CC_QIUNIU_GET_WATCHDOG		5
#define _CC_QIUNIU_GET_CORE_STATUS	6
#define _CC_QIUNIU_START_CORE		7
#define _CC_QIUNIU_STOP_CORE		8

#define _CC_QIUNIU_GET_NET_CONFIG	9
#   define _CC_QIUNIU_NET		0x00000001
#   define _CC_QIUNIU_NET_ETH_P_ALL	0x00000002
#   define _CC_QIUNIU_NET_IPV4		0x00000004
#   define _CC_QIUNIU_NET_ICMP		0x00000008
#   define _CC_QIUNIU_NET_NETROUTING	0x00000010
#   define _CC_QIUNIU_NET_ROUTER	0x00000020
#   define _CC_QIUNIU_NET_UDP		0x00000040
#   define _CC_QIUNIU_NET_AF_PACKET	0x00000080
#   define _CC_QIUNIU_NET_TDMA		0x00000100
#   define _CC_QIUNIU_NET_NOMAC		0x00000200
#   define _CC_QIUNIU_NET_CFG		0x00000400
#   define _CC_QIUNIU_NET_CAP		0x00000800
#   define _CC_QIUNIU_NET_PROXY		0x00001000


enum qiuniu_run_states {
	QIUNIU_STATE_DISABLED,
	QIUNIU_STATE_RUNNING,
	QIUNIU_STATE_STOPPED,
	QIUNIU_STATE_TEARDOWN,
	QIUNIU_STATE_WARMUP,
};

#endif 
