#define CONFIG_MMU 1



#define CONFIG_NECRO_BUILD_STRING "aarch64-unknown-linux-gnu"

#define CONFIG_NECRO_COMPILER "gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) "


#define CONFIG_NECRO_DEFAULT_PERIOD 1000000

#define CONFIG_NECRO_FORTIFY 1

#define CONFIG_NECRO_HEAPMEM 1

#define CONFIG_NECRO_HOST_STRING "aarch64-unknown-linux-gnu"

#define CONFIG_NECRO_LORES_CLOCK_DISABLED 1


#define CONFIG_NECRO_PREFIX "/usr/necro"

#define CONFIG_NECRO_PSHARED 1

#define CONFIG_NECRO_QIUNIU 1

#define CONFIG_NECRO_RAW_CLOCK_ENABLED 1

#define CONFIG_NECRO_REVISION_LEVEL 1

#define CONFIG_NECRO_SANITY 1


#define CONFIG_NECRO_TLS_MODEL "initial-exec"

#define CONFIG_NECRO_UAPI_LEVEL 15


#define CONFIG_NECRO_VERSION_MAJOR 3

#define CONFIG_NECRO_VERSION_MINOR 2

#define CONFIG_NECRO_VERSION_STRING "3.2.1"


#ifdef __IN_NECRO__

#define CONFIG_SMP 1

#define HAVE_BACKTRACE 1

#define HAVE_CLOCK_NANOSLEEP 1

#define HAVE_DECL_PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP 1

#define HAVE_DECL_PTHREAD_PRIO_NONE 1

#define HAVE_DECL_PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP 1

#define HAVE_DLFCN_H 1

#define HAVE_FORK 1

#define HAVE_INTTYPES_H 1

#define HAVE_MQUEUE_H 1

#define HAVE_OBSTACK_H 1

#define HAVE_PTHREAD_ATFORK 1

#define HAVE_PTHREAD_ATTR_SETAFFINITY_NP 1

#define HAVE_PTHREAD_CONDATTR_GETCLOCK 1

#define HAVE_PTHREAD_CONDATTR_SETCLOCK 1

#define HAVE_PTHREAD_GETATTR_NP 1

#define HAVE_PTHREAD_MUTEXATTR_GETPRIOCEILING 1

#define HAVE_PTHREAD_MUTEXATTR_GETPROTOCOL 1

#define HAVE_PTHREAD_MUTEXATTR_SETPRIOCEILING 1

#define HAVE_PTHREAD_MUTEXATTR_SETPROTOCOL 1

#define HAVE_PTHREAD_MUTEXATTR_SETROBUST 1

#define HAVE_PTHREAD_MUTEX_GETPRIOCEILING 1

#define HAVE_PTHREAD_MUTEX_SETPRIOCEILING 1

#define HAVE_PTHREAD_SETAFFINITY_NP 1

#define HAVE_PTHREAD_SETNAME_NP 1

#define HAVE_PTHREAD_SETSCHEDPRIO 1

#define HAVE_PTHREAD_SPIN_LOCK 1

#define HAVE_SCHED_GETCPU 1

#define HAVE_SHM_OPEN 1

#define HAVE_SHM_UNLINK 1

#define HAVE_STDINT_H 1

#define HAVE_STDIO_H 1

#define HAVE_STDLIB_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TYPES_H 1


#define HAVE_UNISTD_H 1

#define LT_OBJDIR ".libs/"

#define PACKAGE "necro"

#define PACKAGE_BUGREPORT "necro@necro.org"

#define PACKAGE_NAME "Necro"

#define PACKAGE_STRING "Necro 3.2.1"

#define PACKAGE_TARNAME "necro"

#define PACKAGE_URL ""

#define PACKAGE_VERSION "3.2.1"

#define STDC_HEADERS 1

#define VERSION "3.2.1"

#define YYTEXT_POINTER 1

#endif 
